export const loading: {
  id: number;
  url: string;
  urlDorada: string;
  percentage: number;
  color: string;
  text: string;
  subtext: string;
}[] = [
  {
    id: 1,
    url: 'assets/NORMAL/CHANCE.png',
    urlDorada: 'assets/DORADOS/CHANCE-DORADO.png',
    percentage: 0,
    color: '#FFFFFF',
    text: 'calculando...',
    subtext: '',
  },
  {
    id: 2,
    url: 'assets/NORMAL/DOBLE-CHANCE.png',
    urlDorada: 'assets/DORADOS/DOBLE-CHANCE---DORADO.png',
    percentage: 0,
    color: '#FFFFFF',
    text: 'calculando...',
    subtext: '',
  },
  {
    id: 3,
    url: 'assets/NORMAL/CHANCE-MILLONARIO.png',
    urlDorada: 'assets/DORADOS/CHANCE-MILLONARIO-DORADO.png',
    percentage: 0,
    color: '#FFFFFF',
    text: 'calculando...',
    subtext: '',
  },
  {
    id: 4,
    url: 'assets/NORMAL/LOGO-PAGA-MAS.png',
    urlDorada: 'assets/DORADOS/LOGO-PAGA-MAS-DORADO.png',
    percentage: 0,
    color: '#FFFFFF',
    text: 'calculando...',
    subtext: '',
  },
  {
    id: 5,
    url: 'assets/NORMAL/LOGO-SUPER-CHANCE.png',
    urlDorada: 'assets/DORADOS/LOGO-DORADO-SUPER-CHANCE.png',
    percentage: 0,
    color: '#FFFFFF',
    text: 'calculando...',
    subtext: '',
  },
  {
    id: 16,
    url: 'assets/NORMAL/TRIPLETAZO.png',
    urlDorada: 'assets/DORADOS/TRIPLETAZO-DORADO.png',
    percentage: 0,
    color: '#FFFFFF',
    text: 'calculando...',
    subtext: '',
  },
  {
    id: 6,
    url: 'assets/NORMAL/LOTERIAS.png',
    urlDorada: 'assets/DORADOS/LOTERIAS-DORADO.png',
    percentage: 0,
    color: '#FFFFFF',
    text: 'calculando...',
    subtext: '',
  },
  {
    id: 7,
    url: 'assets/NORMAL/LOTERIA-VIRTUAL.png',
    urlDorada: 'assets/DORADOS/LOTERIA-VIRTUAL-DORADO.png',
    percentage: 0,
    color: '#FFFFFF',
    text: 'calculando...',
    subtext: '',
  },
  {
    id: 8,
    url: 'assets/NORMAL/RASPA-Y-LISTO.png',
    urlDorada: 'assets/DORADOS/RASPA-Y-LISTO-DORADO.png',
    percentage: 0,
    color: '#FFFFFF',
    text: 'calculando...',
    subtext: '',
  },
  {
    id: 9,
    url: 'assets/NORMAL/BALOTO.png',
    urlDorada: 'assets/DORADOS/BALOTO-DORADO.png',
    percentage: 0,
    color: '#FFFFFF',
    text: 'calculando...',
    subtext: '',
  },
  {
    id: 10,
    url: 'assets/NORMAL/SUPER-GORDO.png',
    urlDorada: 'assets/DORADOS/SUPER-GORDO-DORADO.png',
    percentage: 0,
    color: '#FFFFFF',
    text: 'calculando...',
    subtext: '',
  },
  // {
  //   id: 9,
  //   url: 'assets/NORMAL/SUPER-ASTRO.png',
  //   urlDorada: 'assets/DORADOS/SUPER-ASTRO--DORADO.png',
  //   percentage: 0,
  //   color: '#FFFFFF',
  //   text: 'calculando...',
  //   subtext: '',
  // },
  {
    id: 11,
    url: 'assets/NORMAL/BETPLAY.png',
    urlDorada: 'assets/NORMAL/BETPLAY.png',
    percentage: 0,
    color: '#FFFFFF',
    text: 'calculando...',
    subtext: '',
  },
  {
    id: 12,
    url: 'assets/NORMAL/PAGOS.png',
    urlDorada: 'assets/NORMAL/PAGOS.png',
    percentage: 0,
    color: '#FFFFFF',
    text: 'calculando...',
    subtext: '',
  },
  {
    id: 13,
    url: 'assets/NORMAL/RECARGAS.png',
    urlDorada: 'assets/NORMAL/RECARGAS.png',
    percentage: 0,
    color: '#FFFFFF',
    text: 'calculando...',
    subtext: '',
  },
  {
    id: 14,
    url: 'assets/NORMAL/SUPERGIROS.png',
    urlDorada: 'assets/NORMAL/SUPERGIROS.png',
    percentage: 0,
    color: '#FFFFFF',
    text: 'calculando...',
    subtext: '',
  },
  {
    id: 15,
    url: 'assets/NORMAL/LOGO-AMIGOS-GANE.png',
    urlDorada: 'assets/DORADOS/LOGO-AMIGOS-GANE-DORADO.png',
    percentage: 0,
    color: '#FFFFFF',
    text: 'calculando...',
    subtext: '',
  },
];

export const logosObjects = {
  ch: {
    id: 1,
    name: 'ch',
    url: 'assets/NORMAL/CHANCE.png',
    urlDorada: 'assets/DORADOS/CHANCE-DORADO.png',
  },
  dc: {
    id: 2,
    name: 'dc',
    url: 'assets/NORMAL/DOBLE-CHANCE.png',
    urlDorada: 'assets/DORADOS/DOBLE-CHANCE---DORADO.png',
  },
  cm: {
    id: 3,
    name: 'cm',
    url: 'assets/NORMAL/CHANCE-MILLONARIO.png',
    urlDorada: 'assets/DORADOS/CHANCE-MILLONARIO-DORADO.png',
  },
  pm: {
    id: 4,
    name: 'pm',
    url: 'assets/NORMAL/LOGO-PAGA-MAS.png',
    urlDorada: 'assets/DORADOS/LOGO-PAGA-MAS-DORADO.png',
  },
  cs: {
    id: 5,
    name: 'cs',
    url: 'assets/NORMAL/LOGO-SUPER-CHANCE.png',
    urlDorada: 'assets/DORADOS/LOGO-DORADO-SUPER-CHANCE.png',
  },
  tr: {
    id: 16,
    name: 'sg',
    url: 'assets/NORMAL/TRIPLETAZO.png',
    urlDorada: 'assets/DORADOS/TRIPLETAZO-DORADO.png',
  },

  lf: {
    id: 7,
    name: 'lf',
    url: 'assets/NORMAL/LOTERIAS.png',
    urlDorada: 'assets/DORADOS/LOTERIAS-DORADO.png',
  },
  lv: {
    id: 8,
    name: 'lv',
    url: 'assets/NORMAL/LOTERIA-VIRTUAL.png',
    urlDorada: 'assets/DORADOS/LOTERIA-VIRTUAL-DORADO.png',
  },
  rp: {
    id: 9,
    name: 'rp',
    url: 'assets/NORMAL/RASPA-Y-LISTO.png',
    urlDorada: 'assets/DORADOS/RASPA-Y-LISTO-DORADO.png',
  },
  bl: {
    id: 10,
    name: 'bl',
    url: 'assets/NORMAL/BALOTO.png',
    urlDorada: 'assets/DORADOS/BALOTO-DORADO.png',
  },
  // as: {
  //   id: 10,
  //   name: 'as',
  //   url: 'assets/NORMAL/SUPER-ASTRO.png',
  //   urlDorada: 'assets/DORADOS/SUPER-ASTRO--DORADO.png',
  // },
  sg: {
    id: 6,
    name: 'sg',
    url: 'assets/NORMAL/SUPER-GORDO.png',
    urlDorada: 'assets/DORADOS/SUPER-GORDO-DORADO.png',
  },
  bp: {
    id: 11,
    name: 'bp',
    url: 'assets/NORMAL/BETPLAY.png',
    urlDorada: 'assets/NORMAL/BETPLAY.png',
  },
  pg: {
    id: 12,
    name: 'pg',
    url: 'assets/NORMAL/PAGOS.png',
    urlDorada: 'assets/NORMAL/PAGOS.png',
  },
  rg: {
    id: 13,
    name: 'rg',
    url: 'assets/NORMAL/RECARGAS.png',
    urlDorada: 'assets/NORMAL/RECARGAS.png',
  },
  sp: {
    id: 14,
    name: 'sp',
    url: 'assets/NORMAL/SUPERGIROS.png',
    urlDorada: 'assets/NORMAL/SUPERGIROS.png',
  },
  fd: {
    id: 15,
    name: 'fd',
    url: 'assets/NORMAL/LOGO-AMIGOS-GANE.png',
    urlDorada: 'assets/DORADOS/LOGO-AMIGOS-GANE-DORADO.png',
  },
};
